channels:
  - nvidia/label/cuda-12.4.0
  - nvidia
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - cuda
  - pytorch
  - pytorch-cuda=12.4
  - sysroot_linux-64==2.17
  - torchaudio
  - torchvision
  - pip
  - python=3.10
