[project]
authors = ["fecet <xiezej@gmail.com>"]
channels = ["nvidia/label/cuda-12.4.0", "nvidia", "pytorch", "conda-forge", "nodefaults"]
description = "Add a short description here"
name = "meta-forge"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cuda = "*"
pytorch = "*"
pytorch-cuda = "12.4.*"
sysroot_linux-64 = "==2.17"
torchaudio = "*"
torchvision = "*"
pip = "*"
python = "3.10.*"
