context:
  name: "ml-collections"
  version: "0.1.2"
  git_url: https://github.com/google/ml_collections.git
  git_rev: ${{ git.head_rev( git_url ) }}
  # torch_version: ${{ pytorch | replace('.', '') }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: ${{ git_url }}
    rev: ${{ git_rev }}

build:
  noarch: python
  script:
    - pip install . -vvv --no-deps --no-build-isolation
    # - $PYTHON setup.py install

requirements:
  host:
    - python 3.10
    - pip
  run:
    - absl-py
    - contextlib2
    - six
    - pyyaml
tests:
  - python:
      imports:
        - ml_collections
