context:
  name: "z3-solver"
  git_url: https://github.com/Z3Prover/z3.git
  git_tag: ${{ git.latest_tag( git_url ) }}

package:
  name: ${{ name }}
  version: ${{ git_tag[3:] }}

source:
  - git: ${{ git_url }}
    tag: ${{ git_tag }}

build:
  number: 0
  noarch: python
  script:
    - cd src/api/python
    - |
      export MAX_JOBS=$(( ($CPU_COUNT - 16) < 1 ? 1 : ($CPU_COUNT - 16) ))
    - pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - setuptools >=70
    - pip
    - cmake
  run:
    - python
tests:
  - python:
      imports:
        - z3
