context:
  git_url: https://github.com/sxyazi/yazi.git
  git_tag: ${{ git.latest_tag( git_url ) }}
  name: yazi

package:
  name: ${{ name }}
  version: ${{ git_tag[1:] }}

build:
  script:
    - cargo install --locked yazi-fm yazi-cli --root $PREFIX --no-track

requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ compiler("c") }}

tests:
  - script:
      - yazi --help
