context:
  name: python-ninja
  git_repo_url: https://github.com/scikit-build/ninja-python-distributions
  latest_tag: ${{ git.latest_tag( git_repo_url ) }}
  # version: ${{ latest_tag }}
  version: 1.10.2.3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: ${{ git_repo_url }}
  tag: ${{ latest_tag }}

build:
  script: ${{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - cmake
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - scikit-build
  run:
    - python
    - scikit-build

tests:
  - python:
      imports:
        - ninja
