context:
  package_name: fastuuid
  git_repo_url: https://github.com/fastuuid/fastuuid.git
  latest_tag: ${{ git.latest_tag( git_repo_url ) }}
  version: ${{ latest_tag[1:] }}

package:
  name: ${{ package_name }}
  version: ${{ version }}

source:
  git: https://github.com/fastuuid/fastuuid.git
  # tag: ${{ version }}

build:
  number: 1
  # noarch: python
  # files:
  #   include:
  #     - "**/*"
  #   exclude:
  #     # - $SP_DIR/${{ package_name }}/__pycache__/*
  #     - "**/__pycache__/*"

  script:
    - $PREFIX/bin/pip install . -v
    # - mkdir -p $PREFIX/bin
    # - cp "$RECIPE_DIR/post-link.sh" $PREFIX/bin/.${{package_name}}-post-link.sh
    # - chmod +x $PREFIX/bin/.${{package_name}}-post-link.sh
    # - ls $SP_DIR/${{ package_name }}/__pycache__
    - rm -rf $SP_DIR/${{ package_name }}/__pycache__
  python:
    skip_pyc_compilation:
      # - "__init__.py"
      - "**/__init__.py"
requirements:
  host:
    - maturin
    - pip
    # - python=3.10
    - python

  run:
    - python

tests:
  - python:
      imports:
        - fastuuid
