c_compiler:
  - gcc
c_compiler_version:
  - "12"
c_stdlib:
  - sysroot
c_stdlib_version:
  - "2.17"
cdt_name:
  - cos7
# cuda_compiler:
#   - cuda-nvcc
# cuda_compiler_version:
#   - "12.4"
cxx_compiler:
  - gxx
cxx_compiler_version:
  - "12"
