context:
  name: "platformers"
  version: "0.2.0"
  # torch_version: ${{ pytorch | replace('.', '') }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - path: ../../platformers

build:
  number: ${{ build|int + (microarch_level|int) * 100 + 1 }}
  # merge_build_and_host_envs: false
  # string: py${{ python | version_to_buildstring }}_cuda${{ cuda | version_to_buildstring }}_pt${{ torch_version | version_to_buildstring }}
  noarch: python
  # script:
  #   - pip install . -vvv --no-deps --no-build-isolation
  #   # - $PYTHON setup.py install

requirements:
  host:
    - python 3.10
    - pip
    - poetry
    # host:
  run:
    - cloudpickle
    - pytorch
    - deepspeed
    - safetensors
    - transformers
    - accelerate
    - dm-tree
    - ignite

# tests:
#   - python:
#       imports:
#         - platformers
#       pip_check: false
