context:
  name: "xformers"
  git_url: https://github.com/facebookresearch/xformers.git
  git_tag: ${{ git.latest_tag( git_url ) }}

package:
  name: ${{ name }}
  version: ${{ git_tag[1:] }}

source:
  - git: ${{ git_url }}
    tag: ${{ git.latest_tag( git_url ) }}

build:
  number: ${{ build|int + (microarch_level|int) * 100 + 1 }}
  string: py${{ python | version_to_buildstring }}_cuda${{ cuda | version_to_buildstring }}_pt${{ pytorch | replace('.', '') }}
  script:
    - export CUDA_HOME=$PREFIX
    - $CUDA_HOME/bin/nvcc -V
    - export MAX_JOBS=$(expr $CPU_COUNT - 16)
    - export TORCH_CUDA_ARCH_LIST="8.0+PTX 9.0+PTX"
    - export LDFLAGS="$LDFLAGS -L$PREFIX/lib/stubs"
    - pip install . -vvv --no-deps --no-build-isolation
    # - $PYTHON setup.py install

requirements:
  host:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cuda
    - pytorch-cuda ${{ cuda }}
    - cuda-driver-dev ${{ cuda }}
    - pytorch
    - python
    - pip
    - python-ninja

  run:
    - pytorch
    - fsspec
    - numpy

tests:
  - python:
      imports:
        - xformers

